version: '3.9'

services:
  web:
    build: .
    container_name: resume_analyzer_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - compose.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: resume_db
    restart: always
    env_file:
      - compose.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - compose.env
    depends_on:
      - db

volumes:
  postgres_data:
