version: '3.9'

services:
  web:
    build: .
    container_name: resume_analyzer_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumedb
      - OPENAI_API_KEY=your-gemini-or-openai-key
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: resume_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resumedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Optional pgAdmin GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
